name: CI

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: docker build . --file Dockerfile

  deploy-to-production:
    if: endsWith(github.ref, 'master') == true
    needs: [test]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: bash ./ci-deploy.bash
        env:
          PASSWORD: "${{ secrets.DOCKERHUB_PASSWORD }}"
          USERNAME: "${{ secrets.DOCKERHUB_USERNAME }}"
