name: CI

on: [push]

jobs:
  deploy-to-production:
    if: endsWith(github.ref, 'master') == true
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - run: bash ./ci-deploy.bash
