name: CI

on: [push]

jobs:
  # test:
  #   runs-on: ubuntu-latest
  #   steps:
  #     - uses: actions/checkout@v2
  #     - run: docker build . --file Dockerfile

  deploy-to-production:
    if: endsWith(github.ref, 'master') == true
    # needs: [test]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Log into Docker Hub
        run: echo "${{ secrets.DOCKERHUB_PASSWORD }}" | docker login --username 1mill --password-stdin
      - name: Build image
        run: docker build . --file Dockerfile --tag tmp-image
      - name: Generate version number
        run: VERSION=`date +%Y-%m-%d_%H-%M-%S`
      - name: Tag image
        run: docker tag tmp-image 1mill/terraform-sops:${VERSION}
      - name: Deploy image - versioned
        run: docker push 1mill/terraform-sops:${VERSION}
      - name: Deploy image - latest
        run: docker push 1mill/terraform-sops:latest
