name: CICD

defaults:
  run:
    shell: bash

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: docker-compose build

  deploy-to-production:
    if: endsWith(github.ref, 'master') == true
    needs: [test]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: echo "::set-env name=VERSION::alpine-$(date +'%Y-%m-%dT%H-%M-%S')"
      - run: echo "${{ secrets.DOCKERHUB_PASSWORD }}" | docker login --username ${{ secrets.DOCKERHUB_USERNAME }} --password-stdin
      - run: docker-compose build && docker-compose push
        env:
          VERSION: ${{ env.VERSION }}

on:
  push:
    paths-ignore:
      - '.github/**'
